### ISSUE TITLE
Example crontab not best practice

### ISSUE THREAD

**Issue by carygravel** [Yannik/ansible-role-rsnapshot-backup-host#2]
The example crontab is
```
             - { name: every1h, keep: 12, cronjob: "30 * * * *" }
             - { name: every1d, keep: 3, cronjob: "35 3 * * *" }
             - { name: every1w, keep: 4, cronjob: "0 3 * * 1" }
```
But best practice put the less frequent jobs before the more frequent ones. If I'm not mistaken, in the above, the hourly job runs at 30 mins past the hour, and the daily at 03:35. So there is a danger of the hourly still running when the daily runs. Would it not be better to schedule the daily at "5 3 * * *"?

**Comment by Yannik** [comment]
@carygravel Actually, this variable is no longer used. I have removed it from the README. Due to the concurreny problem mentioned by you, the rotation is now automatically checked after successful sync by `rsnapshot-run.sh` (this also ensures that we don't rotate unless a new sync was actually successfully completed), and rotations are only done sequentially (by `rsnapshot-rotate.sh`)

**Comment by carygravel** [comment]
Cool. Thanks for the explanation. Would it not be a good idea to:
* put the explanation in the docs
* remove the variable

?

**Comment by Yannik** [comment]
> remove the variable

Do you see any places where it needs to be removed, apart from my changes in https://github.com/Yannik/ansible-role-rsnapshot-backup-host/commit/1bb123c74381191338e6f4e0ebab9b02ef7341a8 ?

> put the explanation in the docs

Currently I don't have time for this, and the inner workings can already be understood by reading the code. If somebody else wants to pick this up (there's lots of room for improvement regarding how some of the code is structured, too), I'll gladly review a PR.
